# See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# and https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Documentation update
description: Something new needs to be updated in the Lakebridge documentation
title: "[DOCS]: "
labels: ["needs-triage","documentation"]
type: "task"

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature request you're willing to submit
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Problem statement
      description: A clear and concise description of what the problem is. Ex. The documentation is unclear how to do [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, references or screenshots about the feature request here.
    validations:
      required: false
